### ISSUE TITLE
Automatic fetching and installation of test packages

### ISSUE THREAD

**Issue by aminya** [UziTech/atom-jasmine3-test-runner#124]
It would be nice if atom-jasmine3-test-runner integrates these:

[In my runner file](https://github.com/atom-ide-community/atom-ide-template/blob/master/spec/runner.js#L1-L7), I do something like the following to get the package-deps automatically:
```js
"use babel"
import { createRunner } from "atom-jasmine3-test-runner";
import pkg from "../package.json"

export default createRunner({
  testPackages: Array.from(pkg["package-deps"]), 
}
```

In [`ci.yml`](https://github.com/atom-ide-community/atom-ide-template/blob/master/.github/workflows/CI.yml#L33-L40), there I have written this script to install the deps
```yaml
      - name: Atom Package dependencies
        run: |
          npm install array-to-txt-file
          node -e 'const pkg = require("./package.json"); deps=Array.from(pkg["package-deps"]); const arrayToTxtFile = require("array-to-txt-file"); arrayToTxtFile(deps,"deps.txt", ()=>{});'
          cat deps.txt | \
          while read dep; do
              apm install $dep
          done
```

**Comment by aminya** [comment]
I added a command-line and a js function in https://github.com/steelbrain/package-deps/pull/284, which allows doing this very easily. You can wait for it gets merged and just use that.

**Comment by UziTech** [comment]
It might be better to create a github about to do that. This package is also used locally where the `testPackages` should already be installed. Plus `testPackages` are package names not necessarily the install location. Atom packages can be installed from many different places which why this package assumes the packages are already installed.

**Comment by aminya** [comment]
This added command installs the packages using `apm`. using its `name` or `name@version` or `url`. It is a general command.

Using it inside GitHub actions will be very easy:
```
npm install -g atom-package-deps
package-deps -d .
```

**Comment by UziTech** [comment]
I would rather not couple this package with another packages settings. If atom-package-deps decides to change the settings format or anything I don't want it to break this package.

**Comment by UziTech** [comment]
I'm going to close this as I don't think this will be implemented.
