### ISSUE TITLE
Option to bypass installation

### ISSUE THREAD

**Issue by aminya** [UziTech/atom-jasmine3-test-runner#138]
In a parallel situation that multiple child processes run the tests (or using the shell parallelization), atom-jasmine3-test-runner goes through installing the deps every time. Maybe in version 5.0.0 it does not install them every time, but in the terminal, it is still reported.

I was wondering if we can add a function that we can use to install the deps only once before running the parallel tests and bypass the installation checks for the subsequent runs.

https://github.com/atom-ide-community/atom/pull/57

```
StartedInstalling jasmine-pass

 Executing core render process tests for D:/a/1/s/spec/module-cache-spec.coffee
Installing jasmine-should-fail
Installing jasmine2-tagged
Installing jasmine2-atom-matchers
Installing jasmine2-focused
Installing ./clock
Installing jasmine-local-storage
Installing ./profile
Installing ./set
 Executing core render process tests for D:/a/1/s/spec/native-compile-cache-spec.coffee
Installing jasmine2-json
Installing jasmine-pass
Installing jasmine-should-fail
Installing jasmine2-tagged
Installing jasmine2-focused
Installing ./clock
Installing jasmine-unspy
Installing jasmine-local-storage
Installing ./profile
Installing ./ci
Installing ./set
Installing jasmine-unspy
Installing ./ci
Started

```

**Comment by UziTech** [comment]
The spec helpers would need to run in each process. It doesn't really install them in v5+ so I guess we could suppress the log output but that wouldn't speed it up at all.

**Comment by UziTech** [comment]
I'm going to close this as I don't think there is anything we can do about installing deps once in parallel processes. If there is something you would like to discuss further feel free to reopen this issue.

**Comment by aminya** [comment]
I see there is a "headless" option. How can I enable it?

**Comment by UziTech** [comment]
Running `atom --test spec` in a terminal will set headless to true.

**Comment by aminya** [comment]
Oh, I thought it skips printing messages if it is headless. 

Check this. The repeated printing generates a huge log, which is hard to read. Having an option for skipping installation scripts is necessary, I think. 
https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=868&view=logs&jobId=9e553d4d-6360-5a42-fcf6-9ca3e737bdc9&j=9e553d4d-6360-5a42-fcf6-9ca3e737bdc9&t=bb6a5bb9-c54f-5554-7cdb-6b61724b2d55

**Comment by UziTech** [comment]
I would be fine with a `quiet` option that will suppress the install log. Would you mind creating a PR for that?
