### ISSUE TITLE
TypeScript and CoffeeScript support on the fly

### ISSUE THREAD

**Issue by aminya** [UziTech/atom-jasmine3-test-runner#149]
## Summary

Can we have TypeScript and CoffeeScript support like how `Jest` supports? Currently, compiling these should be done in advance.

## Motivation

Make it easy to write tests in TypeScript and CoffeeScript.

## Describe alternatives you've considered

Compiling tests and src both in advance and then run the tests.

## Additional context

- Jest supports this out of the box
- Mocha has `requires` hook to compile when needed.

**Comment by UziTech** [comment]
Coffeescript works because Atom compiles it on the fly. Typescript could work if Atom adds it to the babel compiler.

**Comment by aminya** [comment]
Oh, I see. if this is a Atom thing, we should fix it in Atom then.

**Comment by UziTech** [comment]
It looks like atom might already have support for typescript files

https://github.com/atom/atom/blob/master/src/typescript.js

**Comment by aminya** [comment]
Yes, it is already there, but as I checked last time, it is only used for the GitHub package. In https://github.com/atom-ide-community/atom/pull/67 I am updating Babel to 7. After that, I have some ideas for the compilers that ship with Atom. 

One of those is to make TypeScript available to everyone.

**Comment by UziTech** [comment]
I'm going to close this as it is something that can be fixed by Atom. I think this package should deal with running tests and leave transpilation to someone else.

**Comment by UziTech** [comment]
It seems this is actually possible with [atom-ts-transpiler](https://www.npmjs.com/package/atom-ts-transpiler). It will work after #169 is merged.

**Comment by aminya** [comment]
Great!
