### ISSUE TITLE
Ability to copy text

### ISSUE THREAD

**Issue by twifty** [UziTech/atom-jasmine3-test-runner#4]
Although the original window doesn't have a 'copy' entry in the context menu, it is still possible to highlight text and copy it with 'ctrl+C'. This feature appears to be missing in `atom-jasmine3-test-runner`.

Would you please add the ability to copy text from the window. And, since we must use the mouse to select text, please add the missing context menu entry.

**Comment by UziTech** [comment]
A PR would be welcome 😃 👍

**Comment by UziTech** [comment]
this should be fixed in v4.2.0
