### ISSUE TITLE
Error in install-dep when using customMatchers

### ISSUE THREAD

**Issue by mrattner** [UziTech/atom-jasmine3-test-runner#7]
Environment details:

- Atom version: 1.32.2
- atom-jasmine3-test-runner version: 4.1.1
- operating system: Linux 64-bit
- I installed Node and npm on my system using [n-install](https://github.com/mklement0/n-install), so the path to my `npm` executable is `/home/marcy/n/bin/npm`.

Steps to reproduce:

1. use a custom atomTestRunner to set the specHelper option:
```
specHelper: {
    customMatchers: true
}
```
2. Run the Atom command **Window: Run Package Specs** to open the test runner window.
3. Tests fail to load with error:
```
Error: Command failed: npm install --no-save --no-package-lock --no-audit jasmine2-atom-matchers@^1.1.0
/bin/sh: 1: npm: not found
```

When I execute the command myself in the same working directory, from a system terminal emulator, the dependency installs OK.

In `spec-helper/install-dep.js`, can the call to `execAsync` know what the system $PATH is? I know there can be some funkiness about $PATH within the context of Atom, so I figured the error has something to do with that :smile:

**Comment by UziTech** [comment]
`execAsync` is just a Promise wrapper around [`child_process.exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback)

by default `exec` creates a separate process running `/bin/sh` on linux. Is it possible there is some configuration on your computer preventing `/bin/sh` from using `$PATH`?

**Comment by mrattner** [comment]
When I run `/bin/sh` in my terminal emulator, within that context `echo $PATH` shows the correct value, and `which npm` is `/home/marcy/n/bin/npm`.

I looked in the Atom forums for similar issues, and found [this thread](https://discuss.atom.io/t/how-to-execute-node-js-child-process-from-package/4880) about Node child processes not always inheriting the correct value for $PATH. Looks like it is a platform-specific issue.

**Comment by UziTech** [comment]
It looks like Atom isn't running as your user and npm is in your user $PATH but not your global $PATH.

I don't know of any way to get Atom to see you user $PATH other than you starting atom from the command line as your user.

**Comment by mrattner** [comment]
I found out more about [how Atom loads its environment](https://github.com/atom/atom/pull/12562) since version 1.12.0, which helped me understand more about what was going on. For anyone else who encounters a similar issue with environment variables in Atom, here is how to fix it:

+ Defining a value for `$NODE_PATH` in your default shell configuration file would fix the issue that I encountered here. Explanation:
    + On Linux and OSX, Atom gets its environment by running the default shell command (e.g. `/bin/sh`) with the arguments `-ilc command env`
    + The only environment variables that it reads, however, are `$NODE_ENV`, `$NODE_PATH`, `$ATOM_HOME`, and `$ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT`.
    + This means that if Atom launches from a desktop shortcut, for example, it will *not* get a value for `$PATH`, but it *will* get a value for `$NODE_PATH`.
+ In the case where you need `$PATH`, or some other variable that Atom does not fetch automatically, you'd need to define it in the appropriate configuration file(s) for your system, which would be loaded by whatever GUI process or shell Atom is launching from.
+ Or, as @UziTech says, just launch Atom in a way that will load the environment you want (e.g. launch it from a login shell, or add arguments to the command that gets executed by a shortcut).

Thanks for the tip about Atom not running as my user--it helped point me in the right direction :slightly_smiling_face:
